### ISSUE TITLE
No more up-to-date data available

### ISSUE THREAD

**Issue by karschau** [0xDanielLopez/TweetFeed#10]
The daily (etc.) feed lists had been updated on 19 July 2023. I suspect that the framework is now broken with Twitter's new policies?

Can anyone confirm?

**Comment by 0xDanielLopez** [comment]
Hello @karschau,

Yes, that's true. Please see [this tweet](https://twitter.com/0xDanielLopez/status/1683754819561947137) where I shared some details.

Hope something changes so I can activate TweetFeed again..

**Comment by xes** [comment]
I'm not sure about current limits, but do you think that a weekly or even monthly update could be managed?

**Comment by 0xDanielLopez** [comment]
Hi @xes, current limit cap of 10k tweets/month makes it impossible to maintain a good flow of updates. If something in X/Twitter API changes I'll try to run TweetFeed again.

**Comment by FANGOD** [comment]
Why not use a crawler?

**Comment by raselahammed** [comment]
![Uploading qrcode.png…]()

**Comment by 0xDanielLopez** [comment]
Hey @karschau / @xes :

Just letting you know that after a long time, I have managed to activate TweetFeed again.

Let me know if you test it or see any bug

I'll give some days to make it "_official_", but it seems good for now 🙌
