### ISSUE TITLE
Default Gateway ip added as IOC

### ISSUE THREAD

**Issue by lestrellacyber** [0xDanielLopez/TweetFeed#13]
Hi, by mistake due to the parsing on this tweet: https://twitter.com/drb_ra/status/1764620344080421175 , the ip address 192.168.0.1 has been added as a indicator of compromise in the following file https://github.com/0xDanielLopez/TweetFeed/blob/master/202403/20240304.csv. I have had problems with remote users which could not connect to their home network.

**Comment by 0xDanielLopez** [comment]
Hi @lestrellacyber, I removed it from the feed.

Thank you very much for flagging this.
