### ISSUE TITLE
Application for Adding an APT Tag

### ISSUE THREAD

**Issue by MrRobotsAA** [0xDanielLopez/TweetFeed#16]
Hi author, I'm applying to add “APT” tags to your system tracking, I hope my suggestion can be considered, thank you very much!

**Comment by 0xDanielLopez** [comment]
Hello,

Sorry for the late response: I considered adding APT as a tag, but there are many other stuff (not infosec related) being posted using this tag - so I avoided using it.

Thanks for the suggestion.
