### ISSUE TITLE
Clarify intervals

### ISSUE THREAD

**Issue by raomin** [0xDanielLopez/TweetFeed#2]
Hi, very nice initiative here, thanks!

For now, week/month/year are a bit misleading as one could understand it as "This week, this month, this year" whereas it seems to be more like "Last 7days, last 30 days, last 365 days". I suggest this should be renamed.

Thanks again.

**Comment by 0xDanielLopez** [comment]
Hi, I have added a new row at Feeds table specifying the intervals for each feed. Hope this helps.

Thanks for the feedback!
