### ISSUE TITLE
TweetFeed with MISP?

### ISSUE THREAD

**Issue by derfel1989** [0xDanielLopez/TweetFeed#3]
Is there any way to integrate TweetFeed with MISP (module)? It would be amazing. 😬

**Comment by derfel1989** [comment]
My apologies for the late reply. I have already set up the integration, and it worked like a charm.

Thank you for your job.

**Comment by AxoniusTK** [comment]
Hey @0xDanielLopez!

Is this still relevant? I see that https://tweetfeed.live/misp/ only has IOCs with old dates.

I would really like to connect TweetFeed with my MISP. :)
