### ISSUE TITLE
Defang URLs

### ISSUE THREAD

**Issue by Maijin** [0xDanielLopez/TweetFeed#4]
Hello o/

I was browsing TweetFeed when I realized the malicious URLs and Domains on the site, for example on search https://tweetfeed.live/search.html are clickable despite the icon seemingly indicating it may just offer a copy in clipboard.

<img width="313" alt="image" src="https://user-images.githubusercontent.com/1408600/171370644-879bf84f-5d73-4799-aee7-22468dd41758.png">
<img width="424" alt="image" src="https://user-images.githubusercontent.com/1408600/171370691-a7be86f3-5934-498a-bca3-8421e9523187.png">

This issue is to suggest to Defang the URLs and Domains to avoid misclicks.

**Comment by 0xDanielLopez** [comment]
Hi @Maijin 

It's interesting. This is the first time someone let me know this issue. 

I have been testing to include another button but doesn't seem "clean" to me:

![image](https://user-images.githubusercontent.com/10616960/171384171-95411664-8b60-4ca1-b6d0-9883ca2d41a6.png)

I have also tested to remove any direct link:

![image](https://user-images.githubusercontent.com/10616960/171386781-17af2581-33e3-4868-ae4c-17b8bbe43116.png)

This way it avoids the possibility of accessing the malicious site by mistake, but also add steps to check several sites (clicking clipboard button -> pasting in browser).

I'll leave active this last version and see the feedback it receives.

Thank you for the issue.
