### ISSUE TITLE
Integrating https://red.flag.domains - suspicious domains from french DNS TLD

### ISSUE THREAD

**Issue by maaaaz** [0xDanielLopez/TweetFeed#6]
Hello @0xDanielLopez,

Do you think you could integrate results from https://red.flag.domains/ ?
It's from this guy: https://twitter.com/_mikolajek_

Cheers !

**Comment by 0xDanielLopez** [comment]
Hey @maaaaz, the repo is intented to collect IOCs on Twitter. No external results for now.

Thank you!
