### ISSUE TITLE
[Feature Request] Provide domain & IP list feeds?

### ISSUE THREAD

**Issue by PeterDaveHello** [0xDanielLopez/TweetFeed#9]
It would be very nice if the feed can be directly consumed with domain and IP list 😃

There are some DNS level blockers like Pi-Hole, blocky, and AdGuard Home, can use domain list as feed without any additional works!

**Comment by 0xDanielLopez** [comment]
Domain and IP lists can be consumed via the API using the following endpoints:

- https://api.tweetfeed.live/v1/today/domain
- https://api.tweetfeed.live/v1/today/ip

*More info/options at https://tweetfeed.live/api.html

You can also use the following command to download these values in raw format:

`curl -s https://api.tweetfeed.live/v1/today | jq -r '.[] | select(.type == "domain") | .value'`

`curl -s https://api.tweetfeed.live/v1/today | jq -r '.[] | select(.type == "ip") | .value'`

However, it is important to note that these lists should not be added directly to a blocklist as there may be false positives. It is recommended to verify the data before adding it to a blocklist.

**Comment by PeterDaveHello** [comment]
Sure, got your point. Thanks!
